#!/usr/bin/env python3
"""Fetch daily weather for each election cycle's early-voting window.

One observation per day for the county as a whole, taken at the county's
centroid — not per site. Early voting spans ~25 miles of Fairfax County,
and the weather that plausibly moves turnout (a washout, a cold snap) is
regional, so a single county-level series is both honest and enough.

Source: Open-Meteo's historical archive (ERA5 reanalysis). Free, no API
key, no attribution requirement beyond the licence note below.

Runs in CI — the dev sandbox has no outbound network.
"""

import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ARCHIVE = "https://archive-api.open-meteo.com/v1/archive"
BOUNDARY = Path("src/data/fairfax-boundary.json")
OUT = Path("data/weather.json")
UA = {"User-Agent": "NovaVote/1.0 (Virginia early-voting turnout site)"}

# Cycle -> inclusive date range to cover. Runs well past Election Day: the
# reports carry post-election rows while late mail is still being received
# (2023 has rows through 11/13), and those days need weather too.
WINDOWS = {
    "fairfax-2023-general": ("2023-09-20", "2023-11-16"),
    "fairfax-2024-general": ("2024-09-18", "2024-11-14"),
    "fairfax-2025-general": ("2025-09-17", "2025-11-16"),
}

# WMO weather codes -> short label. Grouped: the point is "was it the kind
# of day that keeps people home", not meteorological precision.
WMO = {
    0: "Clear", 1: "Mainly clear", 2: "Partly cloudy", 3: "Overcast",
    45: "Fog", 48: "Rime fog",
    51: "Light drizzle", 53: "Drizzle", 55: "Heavy drizzle",
    56: "Freezing drizzle", 57: "Freezing drizzle",
    61: "Light rain", 63: "Rain", 65: "Heavy rain",
    66: "Freezing rain", 67: "Freezing rain",
    71: "Light snow", 73: "Snow", 75: "Heavy snow", 77: "Snow grains",
    80: "Rain showers", 81: "Rain showers", 82: "Violent rain showers",
    85: "Snow showers", 86: "Heavy snow showers",
    95: "Thunderstorm", 96: "Thunderstorm with hail", 99: "Thunderstorm with hail",
}


def county_centroid():
    """Area-weighted centroid of the county's largest ring."""
    doc = json.loads(BOUNDARY.read_text())
    county = next(f for f in doc["features"] if f["role"] == "county")
    ring = max(county["rings"], key=len)
    a = cx = cy = 0.0
    for (x0, y0), (x1, y1) in zip(ring, ring[1:]):
        cross = x0 * y1 - x1 * y0
        a += cross
        cx += (x0 + x1) * cross
        cy += (y0 + y1) * cross
    a *= 0.5
    if a == 0:
        xs = [p[0] for p in ring]
        ys = [p[1] for p in ring]
        return sum(ys) / len(ys), sum(xs) / len(xs)
    return cy / (6 * a), cx / (6 * a)      # lat, lon


def fetch(lat, lon, start, end):
    q = urllib.parse.urlencode({
        "latitude": f"{lat:.4f}",
        "longitude": f"{lon:.4f}",
        "start_date": start,
        "end_date": end,
        "daily": ",".join([
            "weather_code",
            "temperature_2m_max",
            "temperature_2m_min",
            "precipitation_sum",
            "rain_sum",
            "snowfall_sum",
            "wind_speed_10m_max",
        ]),
        "temperature_unit": "fahrenheit",
        "precipitation_unit": "inch",
        "wind_speed_unit": "mph",
        "timezone": "America/New_York",
    })
    req = urllib.request.Request(f"{ARCHIVE}?{q}", headers=UA)
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)


def main():
    if not BOUNDARY.exists():
        sys.exit(f"{BOUNDARY} missing — run scripts/fetch_boundary.py first")
    lat, lon = county_centroid()
    print(f"county centroid: {lat:.4f}, {lon:.4f}", flush=True)

    out = {
        "_comment": (
            "Daily county-level weather for each cycle's early-voting window. "
            "One observation per day at the county centroid, from Open-Meteo's "
            "ERA5 archive. Generated by scripts/fetch_weather.py — do not hand-edit."
        ),
        "source": "https://open-meteo.com/ (ERA5 reanalysis)",
        "licence": "Open-Meteo data under CC BY 4.0",
        "centroid": {"lat": round(lat, 4), "lon": round(lon, 4)},
        "cycles": {},
    }

    for cycle, (start, end) in WINDOWS.items():
        print(f"\n== {cycle}  {start} -> {end}", flush=True)
        payload = fetch(lat, lon, start, end)
        d = payload["daily"]
        days = {}
        for i, date in enumerate(d["time"]):
            code = d["weather_code"][i]
            precip = d["precipitation_sum"][i]
            snow = d["snowfall_sum"][i]
            days[date] = {
                "code": code,
                "label": WMO.get(code, f"code {code}"),
                "tempMax": d["temperature_2m_max"][i],
                "tempMin": d["temperature_2m_min"][i],
                "precip": precip,
                "rain": d["rain_sum"][i],
                "snow": snow,
                "wind": d["wind_speed_10m_max"][i],
                # Pre-computed so the UI doesn't re-derive a judgement call:
                # a quarter inch is roughly "you'd notice it queueing".
                "wet": bool(precip and precip >= 0.25),
                "snowy": bool(snow and snow > 0),
            }
        out["cycles"][cycle] = days

        wet = [k for k, v in days.items() if v["wet"]]
        snowy = [k for k, v in days.items() if v["snowy"]]
        print(f"   {len(days)} days; {len(wet)} with >=0.25in precip; "
              f"{len(snowy)} with snow", flush=True)
        if wet:
            print(f"   wettest: " + ", ".join(
                f"{k} ({days[k]['precip']:.2f}in {days[k]['label']})"
                for k in sorted(wet, key=lambda k: -days[k]["precip"])[:5]), flush=True)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=2) + "\n")
    print(f"\nwrote {OUT} ({OUT.stat().st_size:,} bytes)", flush=True)


if __name__ == "__main__":
    main()
