#!/usr/bin/env python3
"""Download the site's webfonts and self-host them.

Runs in CI (the dev sandbox can't reach Google's font hosts). Writes woff2
files to src/fonts/ plus a generated @font-face stylesheet.

Self-hosting rather than @import-ing from fonts.googleapis.com because:
  * no third-party request on every page load (privacy + latency),
  * the page renders identically in a sandboxed dev environment, where
    the CDN is unreachable and an @import silently falls back,
  * only the weights actually used get shipped.
"""

import re
import sys
import urllib.request
from pathlib import Path

OUT_DIR = Path("src/fonts")
CSS_OUT = Path("src/styles/fonts.css")

# Google's CSS API serves woff2 only to browsers that advertise support.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)

# family -> css2 query. Only the weights the site actually uses; each
# extra weight is a whole extra file, so this list is kept tight.
#   Fraunces  600/700 — headings only (h3 / h1+h2)
#   Source Sans 3  400/600/700 — body, semibold labels, strong
#   IBM Plex Mono  400/500 — tabular figures
FAMILIES = {
    "Fraunces": "Fraunces:opsz,wght@9..144,600;9..144,700",
    "SourceSans3": "Source+Sans+3:wght@400;600;700",
    "IBMPlexMono": "IBM+Plex+Mono:wght@400;500",
}

# This is an English-language site about Virginia elections. The latin-ext
# subset was over half the font payload and is not needed; dropping it
# takes the total from ~900KB to ~350KB.
SUBSETS = ("latin",)

FACE_RE = re.compile(
    r"/\*\s*(?P<subset>[\w\[\]-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]+)\}",
    re.S,
)


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=120) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    blocks = [
        "/* AUTO-GENERATED by scripts/fetch_fonts.py. Do not hand-edit.",
        "   Self-hosted so the page never depends on a third-party font CDN. */",
        "",
    ]
    total = 0

    for slug, query in FAMILIES.items():
        css = get(f"https://fonts.googleapis.com/css2?family={query}&display=swap")
        n = 0
        for m in FACE_RE.finditer(css):
            subset = m.group("subset")
            if subset not in SUBSETS:
                continue
            body = m.group("body")
            url_m = re.search(r"url\((https://[^)]+\.woff2)\)", body)
            if not url_m:
                continue

            style = "italic" if "font-style: italic" in body else "normal"
            weight_m = re.search(r"font-weight:\s*([^;]+);", body)
            weight = weight_m.group(1).strip() if weight_m else "400"
            range_m = re.search(r"unicode-range:\s*([^;]+);", body)

            name = f"{slug}-{subset}-{weight.replace(' ', '_')}-{style}.woff2"
            data = get(url_m.group(1), binary=True)
            (OUT_DIR / name).write_bytes(data)
            total += len(data)
            n += 1

            family = slug_to_family(slug)
            face = [
                "@font-face {",
                f"  font-family: '{family}';",
                f"  font-style: {style};",
                f"  font-weight: {weight};",
                "  font-display: swap;",
                f"  src: url('../fonts/{name}') format('woff2');",
            ]
            if range_m:
                face.append(f"  unicode-range: {range_m.group(1).strip()};")
            face.append("}")
            blocks.append("\n".join(face))

        print(f"[{slug}] {n} face(s)", flush=True)
        if n == 0:
            print(f"  WARNING: no faces captured for {slug}", flush=True)

    CSS_OUT.write_text("\n".join(blocks) + "\n")
    print(f"\nwrote {CSS_OUT} and {total:,} bytes of woff2 to {OUT_DIR}", flush=True)

    if total == 0:
        sys.exit("no fonts downloaded")


def slug_to_family(slug):
    return {
        "Fraunces": "Fraunces",
        "SourceSans3": "Source Sans 3",
        "IBMPlexMono": "IBM Plex Mono",
    }[slug]


if __name__ == "__main__":
    main()
